# Generated by Django 4.2.14 on 2024-07-10 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_alter_emailcredentialstest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcredentialstest',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='emailcredentialstest',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='emailcredentialstest',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, verbose_name='staff status'),
        ),
    ]
